[package]
name = "teg-rw"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["base"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
ron = "0.9"
thiserror = "1.0"

[dependencies]
base = { path = "base" }
